version: '3.2'
services:
  redisdb:
    image: "redis:latest"
    ports:
     - "6379:6379"
  mongo:
    image: "mongo:3.2"
    ports:
     - "27017:27017"
    volumes:
     - ./db/mongo:/data/db
  pangolin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    links:
      - mongo
    depends_on:
      - redisdb
    environment:
      MONGO_URL: mongodb://mongo:27017/ate_way
      REDIS_HOST: redisdb
