version: '3.2'
services:
  ateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    links:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://mongo:27017/ate_way
      REDIS_URL: redis:6379

  redis:
    image: "redis:latest"
    ports:
     - "6379:6379"
  mongo:
    image: "mongo:3.2"
    ports:
     - "27017:27017"