swagger: "2.0"
info:
  description: "Add a Auth layer above API calls"
  version: "1.0.0"
  title: "King Slayer"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api/v1"
schemes:
- "http"
paths: