
plugins:
  - ./plugins/mongo
  - ./plugins/logger
  - ./plugins/swagger
  - ./plugins/externals
  - ./plugins/redis-session
  - ./plugins/policy
  - ./plugins/proxy
  - ./plugins/utils
  - ./plugins/admin_apis
  - ./plugins/monitor

port: 3000
