
plugins:
  - ./plugins/mongo
  - ./plugins/logger
  - ./plugins/swagger
  - ./plugins/externals
  - ./plugins/redis-session
  - ./plugins/policy
  - ./plugins/proxy
  - ./plugins/utils
  - ./plugins/admin_apis

port: 3000

Redis:
  URL: 'localhost:6379'
  nodes:
    - 'localhost:6379'
mongodb:
  url: 'mongodb://localhost:27017/ate_way'